# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCrearDirector():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_crearDirector(self, director):
    self.driver.get("http://localhost:8001/")
    self.driver.set_window_size(1440, 822)
    self.driver.find_element(By.ID, ":r1:-tab-1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\3Ar1\\3A-tabpanel-1 .w-16").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#\\3Ar1\\3A-tabpanel-1 .w-16")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys(director)
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
  
test = TestCrearDirector()
test.setup_method()
test.test_crearDirector("Ron Howard")
test.test_crearDirector("Ridley Scott")
